version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    volumes:
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/book_backup:/usr/share/elasticsearch/es/book_backup
  kibana:
    image: kibana:7.6.0
    container_name: kibana
    restart: always
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es:9200/
    networks:
      - elk
    ports:
      - 5601:5601

networks:
  elk: